### ISSUE TITLE
JPEG is allowing for greater than 3000, api doesn't allow

### ISSUE THREAD

**Issue by panbanda** [uploadcare/nextjs-loader#10]
### Describe the bug

The nextjs loader for JPEG allows for 5000px wide to be uploaded (a constant in the library) yet when the loader loads a jpeg with something smaller than 5000 but more than 3000 the API returns an error saying it can't be larger than 3000.

Failing image:
https://ucarecdn.com/3cdb1700-71c3-43a8-8074-944095e880c8/-/format/auto/-/stretch/off/-/progressive/yes/-/resize/3840x/-/quality/smart/careers-index-hero-person6.jpg

Successful upload:
https://ucarecdn.com/3cdb1700-71c3-43a8-8074-944095e880c8/-/format/auto/-/stretch/off/-/progressive/yes/-/resize/3000x/-/quality/smart/careers-index-hero-person6.jpg

Reference:
https://github.com/uploadcare/nextjs-loader/blob/main/src/utils/constants.ts#L2

### Expected behavior

- allow over 3000 for JPEGs
- or: change the code to only allow 3000 for all images

**Comment by nd0ut** [comment]
Hey @panbanda, thanks for the feedback. We forgot to add `/format/jpeg/` in these cases, I'll fix it asap.

**Comment by nd0ut** [comment]
Done, see [v0.3.2](https://www.npmjs.com/package/@uploadcare/nextjs-loader/v/0.3.2)
