### ISSUE TITLE
Does not support urls without filenames

### ISSUE THREAD

**Issue by aeroheim** [uploadcare/nextjs-loader#13]
### Describe the bug

Passing urls without filenames (i.e https://ucarecdn.com/a6f8abc8-f92e-460a-b7a1-c5cd70a18cdb/) results in various errors in the loader. Did a quick glance through the codebase and it looks like it always assumes a filename and extension exists in the url. According to the official [docs](https://uploadcare.com/docs/delivery/cdn) filenames are completely optional.

See [codesandbox](https://codesandbox.io/s/quizzical-pascal-2zfwu8?file=/pages/index.js) for reproduction.

### Expected behavior
URLs without filenames should work.

**Comment by nd0ut** [comment]
@aeroheim You're right, it's definitely a bug, I'll fix it ASAP. Thanks!

**Comment by kkomelin** [comment]
@nd0ut Good job! Thanks

**Comment by kkomelin** [comment]
Thank you @nd0ut for the new release https://github.com/uploadcare/nextjs-loader/releases/tag/v0.3.3
