### ISSUE TITLE
Images are not compressed

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [uploadcare/nextjs-loader#16]
### Question

I have the following the code down below, When I open the network tab I still see images sent with the original size (10.6MB) without any compression. The second one is the placeholder image I assume. what am I missing?

![newwork](https://user-images.githubusercontent.com/42802922/172189344-9ac9d334-5df4-4dfc-b6f8-c040d271de5b.jpg)
## Relevant information: environment, etc. Please include as much info as possible so we can help you rapidly. 

[demo](https://kartebuch.vercel.app/clients/101/normal)
```js
<UploadcareImage
      layout="responsive"
      width="400"
      height="300"
      loading="lazy"
      placeholder="blur"
      quality="60"
      blurDataURL={"..."}
      src={"..."}
    />
```

**Comment by kkomelin** [comment]
Thanks @Ali-Hussein-dev for your question. Let us investigate.

For the context, the full image urls are:

https://ucarecdn.com/13755151-c2af-45c4-b960-fbd6e082a339/juices.jpg (>10mb)

https://ucarecdn.com/13755151-c2af-45c4-b960-fbd6e082a339/-/format/auto/-/stretch/off/-/progressive/yes/-/resize/1200x/-/quality/lighter/juices.jpg (~56kb)

**Comment by nd0ut** [comment]
Hey @Ali-Hussein-dev
Can you tell me if you're passing a URL pointing to the original image to the `blurDataURL` prop?

**Comment by kkomelin** [comment]
From the Next.js docs:

> [blurDataURL](https://nextjs.org/docs/api-reference/next/image#blurdataurl)
A [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) to be used as a placeholder image before the src image successfully loads. Only takes effect when combined with [placeholder="blur"](https://nextjs.org/docs/api-reference/next/image#placeholder).

> Must be a base64-encoded image. It will be enlarged and blurred, so a very small image (10px or less) is recommended. Including larger images as placeholders may harm your application performance.

https://nextjs.org/docs/api-reference/next/image#blurdataurl

**Comment by nd0ut** [comment]
That's it. 

Unfortunately, we don't support `blurDataURL` props right now. It's value is passed down to the original Next.js Image component without any transformations. As @kkomelin said, it's supposed to be used with base64 encoded images ([see their docs](https://nextjs.org/docs/api-reference/next/image#blurdataurl)). 

But that's an interesting use case, to use images from CDN as the input for the `blurDataURL` prop! I guess we'll be implementing this feature soon.

For now I suggest to build blur image URL by your own, like this:
`https://ucarecdn.com/13755151-c2af-45c4-b960-fbd6e082a339/-/format/auto/-/progressive/yes/-/resize/10x/-/quality/lighter/juices.jpg`

**Comment by Ali-Hussein-dev** [comment]
@nd0ut thank you for your support & the helper function! I appreciate it!

**Comment by nd0ut** [comment]
Hey @Ali-Hussein-dev 
We're released [v0.0.4](https://github.com/uploadcare/nextjs-loader/releases/tag/v0.4.0) with this features so now you can do it in the following way:

```ts
<UploadcareImage
      width="400"
      height="300"
      placeholder="blur"
      src={src}
    />
```

CDN URL value for the `blurDataURL` prop will be generated automatically.

But I would suggest to use static imports if it's possible for you. In that case, `blurDataURL` will be filled with base64 encoded image by Next.js itself and the original image will be proxified though our proxy CDN.

```ts
import image from './local_image.jpg';

<UploadcareImage
      width="400"
      height="300"
      placeholder="blur"
      src={image}
    />
```

**Comment by Ali-Hussein-dev** [comment]
@nd0ut thank you for informing me!
I can't import images statically because they store in Uploadcare, and the image SRCs are in DB. Will that work, though?

**Comment by nd0ut** [comment]
> @nd0ut thank you for informing me!
> I can't import images statically because they store in Uploadcare, and the image SRCs are in DB. Will that work, though?

Yep, this will work
