### ISSUE TITLE
customize upload button style

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [uploadcare/nextjs-loader#19]
Hi, I need to change the button color, I am using Nextjs and couldn't figure out how to achieve that through component props. In the docs, it is all about using Uploacare with vanilla JS.

**Comment by kkomelin** [comment]
The `nextjs-loader` project doesn't provide the upload feature. I think it's better to ask this question in the issue queue of the corresponding project, for example https://github.com/uploadcare/react-widget or https://github.com/uploadcare/uploadcare-widget
